### ISSUE TITLE
Journey to Functional Odysseus + Obsidian MCP Integration on old mac (Intel/Nvidia/Sequioa on OCLP)

### ISSUE THREAD

**Issue by Aladincz** [eskyso/Odysseus-for-obsidian#1]
This is summary of journey of smart monkey 😁 to functional Obsidian wiki connected to Odysseus as it has not went smooth from beggining because of some missteps and lack of knowledge on my side and Ai as well. There is no guarentee all is perfect and you may not face different issue.

Hope it could be helpfull for someone else. Here is AI summary from Lumo, decent model.

# Complete Journey: Odysseus + Obsidian MCP Integration on macOS (Intel/Nvidia/OCLP)

## Overview

This document describes my complete journey from initial setup to fully functional **Odysseus + Obsidian MCP integration** with working RAG (Retrieval-Augmented Generation) on an older Intel Mac with GPU passthrough via OpenCore Legacy Patcher.

If you're trying to integrate **Odysseus** with **Obsidian** using the Model Context Protocol (MCP) and facing issues with ChromaDB, Python versions, or server connectivity — this guide should help.

---

## What We're Building

- **Odysseus Server** (`localhost:7860`) — AI assistant with MCP tools
- **Odysseus MCP Plugin** (`localhost:7077`) — connects Obsidian vault to Odysseus
- **ChromaDB Server** (`localhost:8100`) — vector database for semantic search (RAG)
- **FastEmbed** — local embedding generation (CPU for now)
- **Obsidian Plugin** — interface to query your notes through Odysseus

**Goal:** Ask questions like *"What do I have about Python?"* and get answers based on your Obsidian vault content.

---

## My Hardware/Software Configuration

| Component | Specification |
|-----------|---------------|
| **Machine** | iMac 21.5" i5 2.9GHz, 16GB RAM |
| **GPU** | Nvidia 750M (through OCLP) |
| **OS** | macOS 15.7 (Sonoma/Ventura via OpenCore Legacy Patcher) |
| **Python** | 3.12.14 (NOT 3.14!) |
| **Homebrew** | Standard installation |
| **Obsidian Vault** | Custom folder structure (Raw/Wiki/Archive/Prompts) |

---

## The Problem We Encountered

When first starting out, I faced these critical issues:

### Critical Issues We Faced

| Issue | Cause | Solution |
|-------|-------|----------|
| Python 3.14 installed by Homebrew | ChromaDB incompatible | **Downgrade to Python 3.12** |
| ChromaDB `not reachable` | Server wasn't running | Run `chroma run --port 8100` separately |
| `AttributeError: list_tools` | MCP 2.x breaking change | **Install `mcp<2.0`** |
| Port 7860 `already in use` | Old server still running | Kill with `lsof -ti :7860 \| xargs kill -9` |
| `FastEmbed init failed` | Missing dependency | `pip install fastembed` |
| `venv_odysseus` wrong Python path | Script used old venv | Update `start-macos.sh` to use correct venv |

---

### 1. Install Python 3.12 (CRITICAL!)
> **Why:** ChromaDB 1.5.9 does NOT work with Python 3.14 due to onnxruntime compatibility issues.

```bash
# NOT Python 3.14!
brew install python@3.12
```

### 2. Create Virtual Environment
```bash
cd /Users/[YOUR_USERNAME]/llama.cpp/build/bin/odysseus
python3.12 -m venv venv_odysseus
source venv_odysseus/bin/activate
```
*Your prompt should show `(venv_odysseus)` when activated.*

### 3. Fix `start-macos.sh` Script
*The default script references wrong venv path.*

```bash
sed -i '' 's|./venv/bin/python|./venv_odysseus/bin/python|g' start-macos.sh
```

**Verify:**
```bash
grep "venv_odysseus/bin/python" start-macos.sh
```
*Should show all references updated.*

### 4. Install Dependencies
```bash
pip install -r requirements.txt
```

### 5. Install ChromaDB (Server + Client)
```bash
pip install "chromadb>=1.5.0,<2.0"
```
> **Important:** This installs both client AND server.

### 6. Install FastEmbed (for embeddings)
```bash
pip install fastembed
```
*Without this, RAG initialization fails with:* `FastEmbed init failed: Local fastembed is not installed`

### 7. Install Compatible MCP Version (CRITICAL!)
```bash
pip install "mcp<2.0"
```
> **Why:** MCP 2.x introduced breaking changes — `list_tools()` method removed. You'll get: `AttributeError: 'Server' object has no attribute 'list_tools'`.

### 8. Start ChromaDB Server (Separate Process!)
Open a **NEW** Terminal window/tab:
```bash
cd /Users/[YOUR_USERNAME]/llama.cpp/build/bin/odysseus
source venv_odysseus/bin/activate
chroma run --path ./data/chroma --port 8100
```
*Wait for:* `Chroma server started on http://localhost:8100`  
👉 **Keep this window open! This must run continuously.**

### 9. Stop Any Running Odysseus Server
```bash
lsof -ti :7860 | xargs kill -9
```

### 10. Start Odysseus Server
In your main Terminal:
```bash
python -m uvicorn app:app --host 127.0.0.1 --port 7860
```
*Wait for:*
- `VectorRAG ready (lanes=['fastembed'] docs=0)`
- `MemoryVectorStore initialized`
- `Application startup complete`
- `INFO: Uvicorn running on http://127.0.0.1:7860`

### 11. Configure Obsidian Plugin
1. Open Obsidian → Settings → Community Plugins
2. Browse → "Odysseus for Obsidian" → Install + Enable
3. Go to plugin Settings:
   - Server URL: `http://127.0.0.1:7860`
   - Enable: ON
4. Click Register / Connect

### 12. Verify Everything Works
In Odysseus UI (`http://127.0.0.1:7860`):
- **Settings → Integrations** — All 5 built-in MCP servers should show green ✅ (Memory, Image Generation, RAG, Email, Browser)
- **Settings → Terminal Logs** — Should show no errors after startup
- **Chat** — Try: *What do I have about [topic]?*

---

## Common Errors & Solutions

- **Error:** `Address already in use :7860`
  - **Cause:** Previous server still running
  - **Solution:**
    ```bash
    lsof -ti :7860 | xargs kill -9
    python -m uvicorn app:app --host 127.0.0.1 --port 7860
    ```
- **Error:** `ChromaDB is not reachable at localhost:8100`
  - **Cause:** ChromaDB server not running
  - **Solution:** *(In separate terminal)* `chroma run --path ./data/chroma --port 8100`
- **Error:** `FastEmbed init failed: Local fastembed is not installed`
  - **Cause:** Missing fastembed package
  - **Solution:** `pip install fastembed`
- **Error:** `AttributeError: 'Server' object has no attribute 'list_tools'`
  - **Cause:** MCP 2.x breaking change
  - **Solution:** `pip install "mcp<2.0"`
- **Error:** `MCP package not installed`
  - **Cause:** Wrong Python environment
  - **Solution:** Ensure you're using `venv_odysseus`:
    ```bash
    source venv_odysseus/bin/activate
    pip install mcp
    ```

---

## What Works Now

- ✅ **MCP Connection** — 32 tools registered
- ✅ **Semantic Search** — RAG querying your vault works
- ✅ **Vector Store** — ChromaDB initialized with 12+ entries
- ✅ **Built-in Tools** — Memory, Image, RAG, Email, Browser all active

---

## Known Limitations

- ⚠️ **CPU-only embeddings** — FastEmbed runs on CPU (no GPU acceleration yet)
- ⚠️ **No bulk indexing** — Need to manually trigger vault indexing
- ⚠️ **RAG starts with 0 docs** — Must populate through summarization agent

---

## Final Notes

- **Python 3.12 is critical** — don't try with 3.13 or 3.14
- **Keep ChromaDB running** — separate terminal/process
- **MCP < 2.0** — breaking change in 2.x broke everything
- **FastEmbed is needed** — for RAG to initialize
- **Script must point to correct venv** — update `start-macos.sh`

---

## Contact/Feedback

If this helped you, please leave a comment on this issue! If you hit different problems, share them below.

*Posted by: User who spent 8+ hours debugging this so you don't have to. 😄*

---

## Appendix: Useful Commands

```bash
# Check if ChromaDB is running
curl http://localhost:8100/api/v2/heartbeat

# Check if Odysseus is running
curl http://localhost:7860/api/health

# Find which process is using port 7860
lsof -ti :7860

# Kill all processes using port 7860
lsof -ti :7860 | xargs kill -9

# Check which venv you're in
which python

# Deactivate venv
deactivate
```
